appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jPD4wZMPrGYKNLF4eFLXdcwCtKFAi/dqPQheY0thSrKemssTzfdyveNlY2hPhiBplHA4IP8K+Csnja4qWUpN8pUb2EUtczlQJH3KN6sLiqf9vPZnHuL14V2kLQ67uJeYIlph60koms/e34LnotA9FIXU8/Ngr1uWGLYEFvGlf7qdW/n+yxX3cb4TX2+iL3rGXo1gyeDBR68t/ek82ZnjdH0P2oWL0KMZyH6fDQaBT4cIiEmST1ymDGZ4kNTdXnxEx+BZjfzi0QnxtsMVn7T8rbghq7ifJz+gUkbXih8aamwfckp6RvrGO77VRcnu1Rc9q6ja+8/MTOuuARXUtVEwVGpPkU5KYw9tXdTHC6ovZ6NqD63Fgtfi7eElf41X50P8fTX4ie0eBbiwRQmi+vqbJzKEViHgFInt0Cpz3s/d16o9NJxVgcDp/Qz1ZgGB1RcpGAqYbFPgJCeb7we3W+cKoXUsDsy8PpygJWPp4LEknV+9pAcpTNqTeQMowVuG4LiKz4OjW2jGXlfKtJz5RkN8UXmmthUDYkPVPF2243UvhSnNn6gzrfukABB2K6r0CmVEN0sBR7t/Cziae1zi5iOFSTjZCJluorUbCA05qPKXjd7dyThBygCPP8Mp6lp/CigkZajxk6fmEx4rLphqp0lW6RqS2jVGLpO3ajRIemQf5Qc=}
conda_forge_output_validation: true
