travis:
  secure:
    BINSTAR_TOKEN: YsyhsfAcslliWU53PxdTuruqiFWdR2QUxXMW1ozW/NgGnh7/3N+nS461wSimTBobVGd7yNtGPFmJazjDKFaw11DS+TEQCQvFCetGKEGVKcU7LiZL+h9UWcXGMmQPsKoHFy6pPKBBQ2JyBTbKyttj+KnFUBpGvvzRxU7PRSHByIduMvVjCJqYyG34uR5ZEyAQl5Qvy1D9OfHuayLloLUu7/FlioGrcon+AxqMM8L9647PPF1hFeH5kRy8IsWbdMZQAWyopI2Qzll8n2qvlz5uVuFWN47BqZ/q56QqhFI18zI8XZ6/yB7wBvSnztpzLCzjrH9fvTeqgdxZFtquHUsGfLjUQ7mpI+QZ3dc3c24FTRg21LJ+iHi5ZGs/TBXyTiQbUPYmB0p+z1lbNBMEv9mokOJ0jN67Ov7GJaHzLX5EriSfoG90dIZo9RFkxaOhgNwMwgVwEWloCn46C4ZfDPWx6dm8VYXhqzfD0MmJ9ScM/Xr+m/Cs2NQd7lHVmgwJ2JhMlQqn/fLnX1zrKjxEPpLeOSHgFcZseUJ4xh/aIEpVp6ycTYe7H8Mgyr3GbmxHcj+J+CjjGRfEQu6WK1AAqb3Wll/IbKvOA+DvNdxUaWm1thZJx0DZRN7/K0chV2Q/5KrmpXEl8lLbk/sFhZAjkZga/jRa5A6E3xxy8ejMRrCgFFA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
